name: Build C++ Project

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libpthread-stubs0-dev libopenblas-dev

    - name: Compile train.cpp
      run: |
        g++ train.cpp -o train_linux -O2 -static-libgcc -static-libstdc++ -lpthread -lm
        ls -lh train_linux
        file train_linux

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: train-binary-linux
        path: train_linux
        retention-days: 5
